-- TASK-061: executive overview roll-up columns.
--
-- Adds the totals and denominators an executive roll-up needs to combine
-- child scopes into a parent figure, the graduation counters, and the batch
-- period. Averages cannot be averaged, so the sums are stored alongside them
-- and the parent figure is sum(total) / sum(count).
--
-- Generated by `prisma migrate diff` between the TASK-060 schema state and
-- the TASK-061 schema, so the column types are Prisma's own.
ALTER TABLE "reporting_metrics" ADD COLUMN     "attended_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "final_score_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "graduated_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "graduation_approved_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "graduation_eligible_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "graduation_evaluation_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "period_end" DATE,
ADD COLUMN     "period_start" DATE,
ADD COLUMN     "progress_percent_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "progress_sample_count" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX "reporting_metrics_period_start_period_end_idx" ON "reporting_metrics"("period_start", "period_end");
