import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
  MaxLength,
  Min,
} from 'class-validator';
import {
  LearningContentStatusDto,
  LearningContentTypeDto,
} from './learning-content-status.dto';

/**
 * Content creation is metadata-only. The binary itself is uploaded straight to
 * object storage; this endpoint records where it lives. `objectKey` must already
 * be produced by the file service, so the client never invents a storage path.
 */
export class CreateLearningContentDto {
  @ApiProperty({
    enum: LearningContentTypeDto,
    description: 'FILE stores an object-storage reference; LINK stores a URL',
  })
  @IsEnum(LearningContentTypeDto)
  contentType!: LearningContentTypeDto;

  @ApiProperty({ example: 'Modul 1 — Pengantar' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  title!: string;

  @ApiPropertyOptional({
    description:
      'Object storage key for FILE content. Generated by the file service; never a raw client filename.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(1024)
  objectKey?: string;

  @ApiPropertyOptional({
    description: 'External URL for LINK content',
    example: 'https://contoh.go.id/materi/modul-1.pdf',
  })
  @IsOptional()
  @IsUrl({ require_protocol: true, protocols: ['http', 'https'] })
  @MaxLength(2048)
  externalUrl?: string;

  @ApiPropertyOptional({ example: 'application/pdf' })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  mimeType?: string;

  @ApiPropertyOptional({ minimum: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  sizeBytes?: number;

  @ApiPropertyOptional({ enum: LearningContentStatusDto, default: 'DRAFT' })
  @IsOptional()
  @IsEnum(LearningContentStatusDto)
  status?: LearningContentStatusDto;
}
